os:
  - linux
  - osx

language: node_js

node_js:
  - "4"
  - "6"

script:
  - npm run jsHint -- --failTaskOnError
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]];
    then npm run test -- --failTaskOnError --suppressPassed --excludeCompressedTextures;
    else npm run test -- --failTaskOnError --suppressPassed;
    fi

after_success:
  ## We only need to run coveralls for one node version (doesn't matter which one).
  ## We also ignore publishing failures, since restarting an existing travis build would otherwise break.
  ## Run coverage on OSX and not on linux as Linux will run compressed texture tests which will fail.
  - if [[ "$TRAVIS_OS_NAME" == "osx" && $(node --version) == v6* ]]; then npm run coverage; fi
